### PR TITLE
Bugfix to address issue #6

### LINKED ISSUE #6: cdfsigtrp.f90 - SIGSEGV signal
When using the `cdfsigtrp.f90` to compute the transport of water with density anomaly greater than a given treshold accross a section previously extracted with `cdf_xtrac_brokenline.f90`, i.e., 

```
cdfsigtrp=/your-local-path/CDFTOOLS_jmmp/bin/cdfsigtrp
INPdir=/local-path-to-your-cross-section-file.nc
OUTdir=/local-path-for-your-output
smin=min-density-anomaly-value
smax=max-density-anomaly-value
nbins=1

${cdfsigtrp} -brk ${xFile} -smin ${smin} -smax ${smax} -nbins ${nbins} -teos10

CAUTION : dim names and variable names are now set according to 
  =======   the following namelist : nam_cdf_names
  Equation of state for sea-water : TEOS-10 
  mesh_zgr version is v2.0
  mesh_zgr version is v2.0
  mesh_zgr version is v2.0
  mesh_zgr version is v2.0
  mesh_zgr version is v2.0
  mesh_zgr version is v2.0
  mesh_zgr version is v2.0

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x14b39523e72f in ???
#1  0x40ef74 in ???
#2  0x418021 in ???
#3  0x14b3952295cf in ???
#4  0x14b39522967f in ???
#5  0x403564 in ???
#6  0xffffffffffffffff in ???
Segmentation fault      (core dumped) ${cdfsigtrp} -brk ${xFile} -smin ${smin} -smax ${smax} -nbins ${nbins} -teos10
```
This issue propose a bugfix for this.

### PR DESCRIPTION
**Pull request by oceandie**
This pull request address issue #6.

### CODE REVIEW

**Comment by oceandie** [comment]
The proposed modifications have been successfully tested with GOSI10p3.0 (i.e., the config using local ME s-coord in the GRS area, the exp id is `u-dm257`) and GOSI10p2.1 (i.e., the config using standard z*ps vertical coord., the exp id is `u-dl879`). 
Both configurations uses my bathy-fixes for the Denmark Strait and Faroe Bank Channel.

Below the monthly timeseries of the transport of the overflow water ($\sigma_{\theta} \ge 27.8 \\  kg  \\ m^{-3}$) across the Denmark Strait from GOSI10p2.1 (red) and GOSI10p3 (green) configurations (in black the mean observational value).  
ds_timeseries

**Comment by dcalve** [comment]
It's not clear what the source of the crash is and how this fix addresses it- could you explain further in the issue and PR respectively?

**Comment by oceandie** [comment]
> It's not clear what the source of the crash is and how this fix addresses it- could you explain further in the issue and PR respectively?

OK. As explained in the issue, the code was crashing with `Program received signal SIGSEGV: Segmentation fault - invalid memory reference.`.  This error was due to the fact that arrays `iimina`, `iimaxa`, `ijmina` and `ijmaxa` where initiated without first being allocated - see [L331](https://github.com/JMMP-Group/CDFTOOLS/pull/7/commits/fa0b44d98319fb81c4a8580223b8736a105309f5#diff-941750495ba6d783ea34117f3db5a9c53b9f622f0ef529eaf4c63e0f52e48472L331). 

The changes between [L1984](https://github.com/JMMP-Group/CDFTOOLS/pull/7/commits/fa0b44d98319fb81c4a8580223b8736a105309f5#diff-1fadce3926402ac00d97bd0bd941e679d26d682cadc68e52cddbff80b0a000a9L1984)-[L1990](https://github.com/JMMP-Group/CDFTOOLS/pull/7/commits/fa0b44d98319fb81c4a8580223b8736a105309f5#diff-1fadce3926402ac00d97bd0bd941e679d26d682cadc68e52cddbff80b0a000a9L1990) are needed because when passing in input a section extracted with  [cdf_xtrac_brokenline.f90](https://github.com/JMMP-Group/CDFTOOLS/blob/dev_jmmp/src/cdf_xtrac_brokenline.f90) CDFTOOLS classifies it as `v2.0`, assigning to `clvar` the string `e3v_ps`, which however is not the name of our vertical scale factors and was resulting therefore in an error.

File: src/cdfsigtrp.f90 [hunk 1]
```diff
@@ -327,8 +326,9 @@ PROGRAM cdfsigtrp
...
   ! first call to get nsection and allocate arrays 
   IF ( lbrk ) THEN 
-     npiglo = getdim (cf_brk, cn_x)
-     nsection = 1 ; iimina=1 ; iimaxa=npiglo ; ijmina=1 ; ijmaxa=1
+     !npiglo = getdim (cf_brk, cn_x)
+     !nsection = 1 ; iimina=1 ; iimaxa=npiglo ; ijmina=1 ; ijmaxa=1
+     nsection = 1
   ELSE             
      nsection = 0 
      CALL section_init(cf_section, csection,cvarname,clongname,iimina, iimaxa, ijmina, ijmaxa, nsection)
```
Comment (dcalve) [inline src/cdfsigtrp.f90:334]: Presumably this will also fail because of the unallocated arrays- I note it as a comment rather than something to fix, since it's out of scope of the issue

**Review by dcalve — APPROVED** [review]

File: src/cdfsigtrp.f90 (hunk 1 above)
Comment (oceandie) [reply src/cdfsigtrp.f90:334]: > Presumably this will also fail because of the unallocated arrays- I note it as a comment rather than something to fix, since it's out of scope of the issue

At the beginning I also thought the same - but then, checking `section_init` function, we can see that if `knum==0` (as it is in this case) than the function is only used to determine `nsection`, without initiating any other array - so it will not result in an error.
